"""
FILE: image.py

KYA KARTA HAI:
Ye file Gemini Image Generation API (`gemini-2.5-flash-image`) client calls ko handle karti hai.

RESPONSIBILITY:
Given an image prompt, returns raw binary PNG/JPEG image bytes generated by Gemini's multimodal API.

KON USE KARTA HAI:
- agents/image_planner.py
- services/image_service.py

DEPENDENCIES:
- google-genai -> genai.Client
- config/settings.py -> IMAGE_MODEL_NAME, GOOGLE_API_KEY

REVISION:
image.py = Technical diagram & image generation provider.
"""

import os
from ..config.settings import GOOGLE_API_KEY, IMAGE_MODEL_NAME


def gemini_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by Gemini (model: gemini-2.5-flash-image).
    Requires: pip install google-genai
    Env var: GOOGLE_API_KEY
    """
    from google import genai
    from google.genai import types

    api_key = os.getenv("GOOGLE_API_KEY", GOOGLE_API_KEY)
    if not api_key:
        raise RuntimeError("GOOGLE_API_KEY is not set.")

    client = genai.Client(api_key=api_key)

    resp = client.models.generate_content(
        model=IMAGE_MODEL_NAME,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE"],
            safety_settings=[
                types.SafetySetting(
                    category="HARM_CATEGORY_DANGEROUS_CONTENT",
                    threshold="BLOCK_ONLY_HIGH",
                )
            ],
        ),
    )

    parts = getattr(resp, "parts", None)
    if not parts and getattr(resp, "candidates", None):
        try:
            parts = resp.candidates[0].content.parts
        except Exception:
            parts = None

    if not parts:
        raise RuntimeError("No image content returned (safety/quota/SDK change).")

    for part in parts:
        inline = getattr(part, "inline_data", None)
        if inline and getattr(inline, "data", None):
            return inline.data

    raise RuntimeError("No inline image bytes found in response.")


# ============================================================
# REVISION / CONNECTION MAP
# ============================================================
# Is file ka main kaam: Gemini image generation call handle karna.
# Isko call karta hai: agents/image_planner.py
# Data flow: Prompt String -> gemini_generate_image_bytes() -> Image Bytes
# Shortcut: gemini_generate_image_bytes() = Diagram generation engine.
# ============================================================
